Hello: Hello
Home: Home
ReturnHome: Return Home
MySite: My Site
ThisMySite: This is my site. If you want one then get your own.
Webring: Webring
TicTacToe: Tic-Tac-Toe
Guestbook: Shitboard
HasWebsiteAt: has a website at
AddYourSite: Add Your Site
Submit: Submit
ShitPeopleHavePosted: Shit People Have Posted
SaidOn: said on
PostSomeShit: Post Some Shit
Player: Player
Computer: Computer
Human: Human
Author: Author
Contents: Contents
Url: Url
Owner: Owner
Blog: Blog
PostComment: Post A Comment
PostedOn: on
AnonymousCoward: Anonymous Coward
PostBlogEntry: Post Blog Entry
Title: Title
