Hello: Hola
MySite: Mi Sitio
ThisMySite: Este es mi sitio. Si desea que uno, a continuación, obtenga su propio.
Webring: Anillo Web
TicTacToe: tres en raya
Guestbook: Mierda Pizarra
HasWebsiteAt: tiene un sitio web en
AddYourSite: Añadir Su Sitio Web
Submit: Presentar
ShitPeopleHavePosted: Mierda Gente Han Publicado
SaidOn: dicho en
PostSomeShit: Post Algunos Mierda
Player: Player
Computer: La Máquina
Human: Humanos

