Hello: Salam
Home: Asal
ReturnHome: Pulang Ke Asal
MySite: Laman Saya
ThisMySite: Ini adalah situsku. Jika anda ingin satu kemudian mendapatkan anda sendiri.
Webring: Web Cincin
Guestbook: Lembaga Tahi
HasWebsiteAt: mempunyai lama web di
AddYourSite: Menambah Laman Web Anda
Submit: Memgemukakan
ShitPeopleHavePosted: Orang Najis Telah Menyiarkan
SaidOn: berkata
PostSomeShit: menambah beberapa tahi
Player: Pemain
Computer: Komputer
Human: Manusia

