Hello: Olá
Home: Origem
ReturnHome: Retorno Origem
MySite: Meu Site
ThisMySite: Este é o meu site. Se você quer um, então obter seu próprio.
Webring: Anel da Web
TicTacToe: Jogo Da Velha
Guestbook: Merda Lousa
HasWebsiteAt: tem um site em
AddYourSite: Adicione Seu Site
Submit: Enviar
ShitPeopleHavePosted: Merda Pessoas Postaram
SaidOn: disse em
PostSomeShit: Poste Alguma Merda
Player: Player
Computer: Computador
Human: Humano
Author: Autor
Owner: Dono
Url: Endereço

