Hello: Merhaba
Home: Ev
ReturnHome: Eve Dönüş 
MySite: Sitesi
ThisMySite: Bu benim sitedir. Birine sahip olmak istiyorsanız o zaman kendin alabilirsiniz.
Webring: Ağhalka 
TicTacToe: tic-tac-toe 
Guestbook: Bok Tahta
HasWebsiteAt: sitesi aittir göre
AddYourSite: Sitenizi Ekleyin 
Submit: Gönderin 
ShitPeopleHavePosted: bok insanlar asmak
SaidOn: tarihte söyledi
PostSomeShit: asmak bazı bok
Player: Oyuncu 
Computer: Bilgisayar 
Human: İnsan
Author: Yaratıcı
Owner: Sahip
Contents: Içindekiler
Url: Adresi
